name: Cron Workflow

on:
  schedule:
    - cron: '*/1 * * * *'   # runs every 1 minute

jobs:
  cron-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Cron step
        run: |
          echo "Hello Cron workflow"
          echo "Hello world"
