name: Dependent Multi Jobs Workflow

on: 
  workflow_dispatch:

jobs:
  first-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: First Workflow Job
        run: |
          echo "Hello First Workflow job"

  second-workflow-job:
    runs-on: ubuntu-latest
    needs: [first-workflow-job]

    steps:
      - name: Second Workflow Job
        run: |
          echo "Hello Second Workflow job"      

  third-workflow-job:
    runs-on: ubuntu-latest
    needs: [first-workflow-job, second-workflow-job]

    steps:
      - name: Third Workflow Job
        run: |
          echo "Hello Third Workflow job"                
