name: Value Pass Workflow

on: 
  workflow_dispatch:
    inputs:
      name: 
        description: 'Enter your name'
        required: true
        default: 'Unamed'

jobs:
  get-value-workflow-job:
    runs-on: ubuntu-latest
    outputs: 
      greetings_message: ${{ steps.generate-message.outputs.message }}

    steps:
      - name: Generate Greeting message
        id: generate-message
        run: |
          echo "message=Hello, ${{ github.event.inputs.name }}!" >> $GITHUB_OUTPUT

  print-value-workflow-job:
    runs-on: ubuntu-latest
    needs: [get-value-workflow-job]

    steps:
      - name: Print Greeting message
        run: |
          echo "${{ needs.get-value-workflow-job.outputs.greetings_message }}"        
        
